---
# Handlers for the hadoop master services

- name: restart hadoop master services
  service: name=${item} state=restarted
  with_items: 
    - hadoop-0.20-mapreduce-jobtracker
    - hadoop-hdfs-namenode
