---
# Playbook for  Hadoop slave servers

- name: Install the datanode and tasktracker packages
  apt: name={{item}} state=installed update_cache=yes
  with_items: 
   - hadoop-yarn-nodemanager
   - hadoop-mapreduce
   - hadoop-hdfs-datanode

- name: copy hadoop data node config files
  copy: src=roles/hadoop_slave/files/conf/{{ item }} dest=/etc/hadoop/conf/{{ item }} owner=root group=hadoop
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - slaves
    - mapred-site.xml
    - yarn-site.xml
  notify: restart hadoop slave services
  tags: hadoop_master

- name: Create the data directory for the slave nodes to store the data
  file: path={{ item }} owner=hdfs group=hdfs state=directory
  with_items: 
    - /data/1/dfs/dn
    - /data/2/dfs/dn
    - /data/3/dfs/dn

- name: Create the data directory for the slave nodes for yarn
  file: path={{ item }} owner=yarn group=yarn state=directory
  with_items:
    - /data/1/yarn/local
    - /data/2/yarn/local
    - /data/3/yarn/local
    - /data/4/yarn/local
    - /data/1/yarn/logs
    - /data/2/yarn/logs
    - /data/3/yarn/logs
    - /data/4/yarn/logs
   
- name: start hadoop datanode services
  service: name={{ item }} state=started
  with_items:
    - hadoop-hdfs-datanode
    - hadoop-yarn-nodemanager
  tags: yarn
