---
# file: roles/hadoop_master/tasks/main.yml

- name: Install the namenode and jobtracker packages
  apt: name={{ item }} update_cache=yes
  tags: hadoop_master
  with_items:
    - hadoop-client
    - hadoop-hdfs-namenode
    - hadoop-yarn-resourcemanager
    - hadoop-yarn-proxyserver
    - hadoop-mapreduce-historyserver

- name: copy hadoop name node config files
  copy: src=roles/hadoop_master/files/conf/{{ item }} dest=/etc/hadoop/conf/{{ item }} owner=root group=hadoop
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - slaves
    - mapred-site.xml
    - yarn-site.xml
  notify: restart hadoop master services
  tags: hadoop_master

- name: make celos defaults dir
  file: path=/etc/celos/defaults state=directory
  tags: hadoop_master

- name: copy celos defaults
  copy: src=roles/hadoop_master/files/collective.js dest=/etc/celos/defaults/collective.js
  tags: hadoop_master

- name: make name node dirs
  file: path={{ item }} owner=hdfs group=hdfs state=directory
  tags: hadoop_master
  with_items:
    - /var/lib/hadoop-hdfs/cache/hdfs/dfs/name

- name: Format the namenode
  shell: creates=/usr/lib/hadoop/namenode.formatted su - hdfs -c "hadoop namenode -format" && touch /usr/lib/hadoop/namenode.formatted
  tags: hadoop_master

- name: start hadoop namenode services
  service: name=hadoop-hdfs-namenode state=started
  tags: hadoop_master

- name: Give permissions for mapred users
  shell: creates=/usr/lib/hadoop/namenode.initialized su - hdfs -c "hadoop fs -chown hdfs:hadoop /"; su - hdfs -c "hadoop fs -chmod 0775 /" && touch /usr/lib/hadoop/namenode.initialized

