---
# Playbook to deploy the current Celos source to the cluster.
#
# Copies src/, scripts/, and Buildfile into ~/celos-deploy on the Hadoop master.
#
# Then builds the WAR and deploys it to Tomcat using scripts/war-deploy.sh.

- hosts: hadoop_masters
  gather_facts: no
  remote_user: celos
  vars:
    local_celos: ..
    remote_celos: ~/deploy

  tasks:

  - name: Remove old files
    shell: rm -rf {{remote_celos}}/*

  - name: Copy files
    local_action: command rsync -az -e ssh {{local_celos}}/Buildfile {{local_celos}}/core {{local_celos}}/interfaces {{local_celos}}/scripts {{local_celos}}/samples
      celos@{{inventory_hostname}}:{{remote_celos}}

  - name: Build
    shell: cd {{remote_celos}} && buildr TEST=no package

  - name: Deploy WAR
    shell: cd {{remote_celos}} && ./scripts/war-deploy.sh
