---
# Playbook to perform integration testing on Celos
#
# Uploads sample workflows to the Celos master node and verifies that
# the result of the /celos/workflow-list servlet lists the workflows.

- hosts: hadoop_masters
  gather_facts: no
  vars:
    local_celos: ..
    celos_port: 8080
    celos_workflows_dir: /etc/celos/workflows
    celos_db_dir: /var/lib/celos/db
    celos_user: ubuntu

  tasks:

  # TODO: move these 2 to celos_deploy

  - name: Prepare configuration dir
    shell: sudo rm -rf {{celos_workflows_dir}}/* && sudo mkdir -p {{celos_workflows_dir}}
      && sudo chown {{celos_user}}:{{celos_user}} {{celos_workflows_dir}}

  - name: Prepare database dir
    shell: sudo rm -rf {{celos_db_dir}}/* && sudo mkdir -p {{celos_db_dir}}
      && sudo chown {{celos_user}}:{{celos_user}} {{celos_db_dir}}

  - name: Testing servlet /celos/workflow-list with empty configuration
    local_action: shell curl {{inventory_hostname}}:8080/celos/workflow-list | diff - test_files/empty_workflow_list.json

  - name: Upload sample workflow configuration files
    local_action: command rsync -az -e ssh {{local_celos}}/src/test/resources/com/collective/celos/workflow-configuration-test/json-workflow-list-servlet-test/
      {{celos_user}}@{{inventory_hostname}}:{{celos_workflows_dir}}

  - name: Testing servlet /celos/workflow-list with non-empty configuration
    local_action: shell curl {{inventory_hostname}}:8080/celos/workflow-list | diff - test_files/workflow_list.json
