---
# Playbook to perform integration testing on Celos
#
# Performs various tests against the servlets.

- hosts: hadoop_masters
  gather_facts: no
  remote_user: celos
  vars:
    local_celos: ..
    celos_port: 8080
    celos_workflows_dir: /etc/celos/workflows
    celos_db_dir: /var/lib/celos/db

  tasks:

  # TODO: move these 2 to celos_deploy

  - name: Prepare configuration dir
    shell: sudo rm -rf {{celos_workflows_dir}}/* && sudo mkdir -p {{celos_workflows_dir}}
      && sudo chown celos:celos {{celos_workflows_dir}}

  - name: Prepare database dir
    shell: sudo rm -rf {{celos_db_dir}}/* && sudo mkdir -p {{celos_db_dir}}
      && sudo chown celos:celos {{celos_db_dir}}

  - name: Check servlet /celos/scheduler responds to POST
    local_action: shell curl --fail -X POST {{inventory_hostname}}:8080/celos/scheduler

  - name: Check servlet /celos/scheduler doesn't respond to GET
    local_action: shell ! curl --fail {{inventory_hostname}}:8080/celos/scheduler

  - name: Testing servlet /celos/workflow-list with empty configuration
    local_action: shell curl {{inventory_hostname}}:8080/celos/workflow-list | diff - test_files/empty_workflow_list.json

  - name: Upload sample workflow configuration files
    local_action: command rsync -az -e ssh {{local_celos}}/src/test/resources/com/collective/celos/workflow-configuration-test/json-workflow-list-servlet-test/
      celos@{{inventory_hostname}}:{{celos_workflows_dir}}

  - name: Testing servlet /celos/workflow-list with non-empty configuration
    local_action: shell curl {{inventory_hostname}}:8080/celos/workflow-list | diff - test_files/workflow_list.json
