---
# file: roles/hadoop_master/tasks/main.yml

- name: Install the oozie packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - oozie
    - oozie-client
    - libmysql-java
  tags: oozie


- name:  Create  oozie database
  mysql_db: name=oozie state=present collation=utf8_general_ci
  tags: oozie

- name: Create demo database user
  mysql_user: name=oozie password=oozie priv=*.*:ALL host=localhost state=present
  tags: oozie

- name: Oozie site.xml config file
  copy: src=roles/oozie/files/oozie-site.xml dest=/etc/oozie/conf/oozie-site.xml
  notify: restart oozie services
  tags: oozie

- name: Oozie tomcat config
  shell: update-alternatives --set oozie-tomcat-conf /etc/oozie/tomcat-conf.http
  notify: restart oozie services
  tags: oozie

- name: Oozie oozie-env.sh config file
  copy: src=roles/oozie/files/oozie-env.sh dest=/etc/oozie/conf/oozie-env.sh
  notify: restart oozie services
  tags: oozie

- name: Link mysql jdbc jar to oozie
  file: src=/usr/share/java/mysql.jar dest=/var/lib/oozie/mysql-connector.jar state=link
  tags: oozie

- name: Run oozie database tool
  shell: creates=/usr/lib/oozie/oozie.databased sudo -u oozie /usr/lib/oozie/bin/ooziedb.sh create -run && touch /usr/lib/oozie/oozie.databased 
  tags: oozie

- name: Make oozie home dir in hdfs
  shell: creates=/usr/lib/oozie/oozie.homedired su - hdfs -c " hadoop fs -mkdir /user &&  hadoop fs -mkdir  /user/oozie && hadoop fs -chown oozie:oozie /user/oozie" && touch /usr/lib/oozie/oozie.homedired
  tags: oozie

- name: untar oozie sharelib
  shell: creates=/tmp/ooziesharelib/untarred mkdir -p /tmp/ooziesharelib/share && /bin/tar -C /tmp/ooziesharelib/share --strip-components 1 -zxf /usr/lib/oozie/oozie-sharelib-yarn.tar.gz && touch /tmp/ooziesharelib/untarred 
  tags: oozie

- name: Upload sharelib to hdfs
  shell: creates=/usr/lib/oozie/sharelibs.uploaded sudo  -u oozie hadoop fs -put /tmp/ooziesharelib/share /user/oozie/share  && touch /usr/lib/oozie/sharelibs.uploaded
  tags: oozie

- name: Start oozie service
  service: name=oozie state=started
  tags: oozie

- name: set OOZIE_URL
  lineinfile: dest=/etc/environment state=present
    regexp="^OOZIE_URL="
    line="OOZIE_URL=http://localhost:11000/oozie"
  tags: oozie
